# Generated by Django 5.1.1 on 2024-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=25)),
                ('productQty', models.IntegerField()),
                ('productPrice', models.FloatField()),
                ('productTotal', models.IntegerField()),
                ('productDesc', models.CharField(max_length=25)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('emailAddress', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
